# Generated by Django 5.1.1 on 2024-09-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categories_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sub_category',
            new_name='upper_category',
        ),
    ]
