# Generated by Django 5.1.1 on 2024-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='seo_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
