# Generated by Django 5.1.1 on 2024-09-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_tags_products_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
