# Generated by Django 5.1.1 on 2025-01-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variations_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='versionspictures'),
        ),
    ]
